import type { Audience, GeneratorInputField, GeneratorTool, ResultKind } from "../types";
import { POKEMON_TYPES } from "../data/pokemon";
import { todayIsoDate } from "../../../../shared/text";

const CATEGORY_LABELS: Record<Audience, string> = {
	Design: "Design",
	Engineering: "Code",
	Gaming: "Gaming",
	Geographic: "Geographic",
	Identifiers: "Identifiers",
	People: "People",
	Product: "Product",
	Random: "Random",
	Security: "Security",
	Strings: "Text",
	TestData: "Test data",
	Tools: "Tools",
};
const NO_INPUT_TOOL_IDS = new Set([
	"coinflip",
	"company",
	"coordinates",
	"iban",
	"ip-address",
	"ipv4",
	"ipv6",
	"mac",
	"minecraft-seed",
	"minecraft-uuid",
	"ssh-key",
	"us-state",
	"uuid",
	"zodiac",
	"zip",
]);
const GENERATOR_ALIASES: Partial<Record<string, readonly string[]>> = {
	"api-key": ["api-keys"],
	"api-token": ["api-tokens"],
	"barcode": ["barcodes"],
	"bearer-token": ["bearer-tokens"],
	"card": ["credit-cards"],
	"coinflip": ["coin-flip"],
	"colour": ["color", "colors", "colours"],
	"company": ["company-names"],
	"date": ["dates"],
	"datetime": ["date-time", "datetimes"],
	"emoji": ["emojis"],
	"emoji-image": ["emoji-images"],
	"encryption-key": ["encryption-keys"],
	"fraction": ["fractions"],
	"hash": ["hashes"],
	"hex-number": ["hexadecimal-number", "hexadecimal-numbers"],
	"iban": ["ibans"],
	"ip-address": ["ip", "ip-addresses"],
	"ipv4": ["ipv4-address", "ipv4-addresses"],
	"ipv6": ["ipv6-address", "ipv6-addresses"],
	"jwt-token": ["jwt-tokens"],
	"mac": ["mac-address", "mac-addresses"],
	"minecraft-seed": ["minecraft-seeds"],
	"number": ["numbers"],
	"octal-number": ["octal-numbers"],
	"binary": ["binary-number", "binary-numbers"],
	"oauth-token": ["oauth-tokens"],
	"passphrase": ["passphrases"],
	"password": ["passwords"],
	"person": ["persons"],
	"phone": ["phone-number", "phone-numbers"],
	"pin": ["pin-code", "pin-codes"],
	"port-number": ["port-numbers"],
	"qr": ["qr-code", "qr-codes"],
	"salt": ["salts"],
	"ssh-key": ["ssh-keys"],
	"string": ["strings"],
	"time": ["times"],
	"timestamp": ["timestamps"],
	"us-state": ["us-states"],
	"username": ["usernames"],
	"uuid": ["uuids"],
	"webhook-secret": ["webhook-secrets"],
	"zodiac": ["zodiac-sign", "zodiac-signs"],
	"zip": ["zip-code", "zip-codes", "post-code", "postcodes", "postcode", "postal-code", "postal-codes"],
};

function createGeneratorTools(): readonly GeneratorTool[] {
	return [
	tool("qr", "QR image", "Engineering", "QR image for links and notes.", "Input", true, "https://pashi.app", "image", "generate QR", ["https://pashi.app", "https://nicholasgriffin.dev/docs"]),
	tool("barcode", "Barcode", "Engineering", "Code 128 barcode SVG.", "Value", true, "PASHI-12345", "image", "Generate barcode", ["PASHI-12345", "ORDER-2048"], [
		field("value", "Value", "PASHI-12345", true),
		field("height", "Height", "160", true),
		field("scale", "Scale", "2", true),
		field("text", "Text", "show", false, "select", ["show", "hide"]),
	]),
	tool("emoji-image", "Emoji image", "Design", "Square SVG emoji image.", "Emoji", false, "⚡", "image", "Generate image", ["⚡", "✨"], [
		field("emoji", "Emoji", "⚡", true),
		field("size", "Size", "512", true),
		field("background", "Background", "0d1024", true),
	]),
	tool("uuid", "UUID", "Engineering", "UUIDs across versions v1, v3, v4, v5 and v7.", "Count", false, "1", "text", "Generate UUID", ["1", "10"], [
		field("count", "Count", "1", true),
		field("format", "Format", "v4", false, "select", ["v1", "v3", "v4", "v5", "v7"]),
		field("outputFormat", "Output format", "standard", false, "select", ["standard", "uppercase", "no-hyphens", "braced", "urn"]),
		field("name", "Name", "name", false),
		field("namespace", "Namespace", "url", false),
	]),
	tool("token", "Token", "Engineering", "URL-safe random tokens.", "Length", false, "32", "text", "Generate token", ["32", "48"], [
		field("length", "Length", "32", true),
		field("count", "Count", "1", true),
	]),
	tool("api-token", "API token", "Security", "API tokens with selectable encoding.", "Length", false, "32", "text", "Generate API token", ["32", "64"], [
		field("count", "Count", "10", true),
		field("length", "Length", "32", true),
		field("format", "Format", "alphanumeric", false, "select", ["alphanumeric", "hex", "base64", "base64url"]),
		field("prefix", "Prefix", "token_", false),
	]),
	tool("password", "Password", "Security", "Strong passwords with configurable character sets.", "Length", false, "16", "text", "Generate password", ["16", "32"], [
		field("length", "Length", "16", true),
		field("count", "Count", "5", true),
		field("uppercase", "Uppercase", "true", false, "select", ["true", "false"]),
		field("lowercase", "Lowercase", "true", false, "select", ["true", "false"]),
		field("numbers", "Numbers", "true", false, "select", ["true", "false"]),
		field("symbols", "Symbols", "true", false, "select", ["true", "false"]),
		field("excludeSimilar", "Exclude similar", "false", false, "select", ["false", "true"]),
		field("customSymbols", "Custom symbols", "!@#$%^&*()_+-=[]{}|;:,.<>?", false),
	]),
	tool("hash", "Hash", "Security", "MD5 and SHA hashes for text or random data.", "Input", false, "Text to hash", "fields", "Generate hash", ["hello world", "sha256"], [
		field("value", "Text", "hello world", false, "textarea"),
		field("algorithm", "Algorithm", "sha256", true, "select", ["md5", "sha1", "sha256", "sha512"]),
		field("count", "Count", "1", true),
		field("uppercase", "Uppercase", "false", false, "select", ["false", "true"]),
		field("includeInput", "Include input", "false", false, "select", ["false", "true"]),
	]),
	tool("api-key", "API key", "Security", "API keys with selectable formats and optional secrets.", "Length", false, "32", "fields", "Generate key", ["32", "64"], [
		field("count", "Count", "1", true),
		field("length", "Length", "32", true),
		field("format", "Format", "alphanumeric", false, "select", ["alphanumeric", "hex", "base64", "base64url", "uuid", "numeric"]),
		field("prefix", "Prefix", "sk_", false),
		field("includeSecret", "Include secret", "false", false, "select", ["false", "true"]),
		field("keyLength", "Key length", "32", true),
		field("secretLength", "Secret length", "64", true),
		field("keyPrefix", "Key prefix", "key_", false),
		field("secretPrefix", "Secret prefix", "secret_", false),
	]),
	tool("jwt-token", "JWT token", "Security", "Signed JWTs with HMAC or RSA algorithms and configurable claims.", "Subject", false, "user_123", "fields", "Sign JWT", ["user_123", "RS256"], [
		field("count", "Count", "1", true),
		field("algorithm", "Algorithm", "HS256", false, "select", ["HS256", "HS384", "HS512", "RS256", "RS384", "RS512"]),
		field("subject", "Subject", "user_123", true),
		field("issuer", "Issuer", "pashi", true),
		field("audience", "Audience", "https://api.example.com", false),
		field("expiresIn", "Expires in seconds", "3600", true),
		field("includeNbf", "Include nbf", "false", false, "select", ["false", "true"]),
		field("includeJti", "Include jti", "true", false, "select", ["true", "false"]),
		field("customClaims", "Custom claims JSON", "{\"role\":\"admin\"}", false, "textarea"),
	]),
	tool("oauth-token", "OAuth token", "Security", "OAuth 2.0 token response with optional refresh token.", "Length", false, "64", "fields", "Generate OAuth", ["64"], [
		field("count", "Count", "1", true),
		field("tokenType", "Token type", "bearer", false, "select", ["bearer", "mac", "basic"]),
		field("format", "Format", "base64url", false, "select", ["base64", "base64url", "hex", "alphanumeric"]),
		field("accessTokenLength", "Access length", "64", true),
		field("refreshTokenLength", "Refresh length", "128", true),
		field("expiresIn", "Expires in seconds", "3600", true),
		field("scope", "Scope", "read write", false),
		field("includeRefresh", "Include refresh", "true", false, "select", ["true", "false"]),
	]),
	tool("webhook-secret", "Webhook secret", "Security", "Webhook HMAC secret with optional signature example.", "Length", false, "32", "fields", "Generate secret", ["32"], [
		field("count", "Count", "1", true),
		field("length", "Length", "32", true),
		field("algorithm", "Algorithm", "sha256", false, "select", ["sha256", "sha384", "sha512"]),
		field("format", "Format", "hex", false, "select", ["hex", "base64", "alphanumeric"]),
		field("includeExample", "Include example", "true", false, "select", ["true", "false"]),
		field("includeTimestamp", "Include timestamp", "false", false, "select", ["false", "true"]),
	]),
	tool("encryption-key", "Encryption key", "Security", "AES, HMAC, and RSA key material with selectable output formats.", "Algorithm", false, "aes", "fields", "Generate key", ["aes", "rsa"], [
		field("count", "Count", "1", true),
		field("algorithm", "Algorithm", "aes", false, "select", ["aes", "hmac", "rsa"]),
		field("keySize", "Key size", "256", true, "select", ["128", "192", "256", "384", "512", "2048", "4096"]),
		field("format", "Format", "hex", false, "select", ["hex", "base64", "base64url", "pem"]),
		field("includeIv", "Include IV", "true", false, "select", ["true", "false"]),
	]),
	tool("salt", "Salt", "Security", "Cryptographic salt with selectable encoding.", "Length", false, "32", "fields", "Generate salt", ["16", "32"], [
		field("length", "Length", "32", true),
		field("encoding", "Encoding", "base64", false, "select", ["base64", "base64url", "hex", "alphanumeric"]),
		field("count", "Count", "1", true),
		field("includeLength", "Include length", "false", false, "select", ["false", "true"]),
	]),
	tool("ssh-key", "SSH key", "Security", "RSA SSH key pair with authorized_keys public output.", "Options", false, "", "fields", "Generate SSH", ["rsa", "deploy@ci-server"], [
		field("count", "Count", "1", true),
		field("type", "Type", "rsa", false, "select", ["rsa"]),
		field("bits", "Bits", "2048", false, "select", ["2048", "4096"]),
		field("format", "Format", "both", false, "select", ["both", "pem"]),
		field("comment", "Comment", "pashi@localhost", false),
	]),
	tool("bearer-token", "Bearer token", "Security", "Ready-to-paste bearer token header value.", "Bytes", false, "48", "text", "Generate bearer", ["48"], [
		field("bytes", "Bytes", "48", true),
		field("count", "Count", "1", true),
	]),
	tool("port-number", "Port number", "Security", "Random TCP/UDP port in a range.", "Range", false, "1024-65535", "text", "Generate port", ["1024-65535"], [
		field("min", "Min", "1024", true),
		field("max", "Max", "65535", true),
		field("count", "Count", "1", true),
	]),
	tool("base64", "Base64", "Engineering", "Base64 encode text.", "Input", true, "Text to encode", "text", "Encode", ["hello world", "{\"ok\":true}"]),
	tool("url", "URL encode", "Engineering", "URL encode text.", "Input", true, "Text or URL", "text", "Encode URL", ["hello world", "https://nicholasgriffin.dev/?q=hello world"]),
	tool("slug", "Slug", "Engineering", "Safe URL slug.", "Input", true, "Launch notes v2", "text", "Make slug", ["My Great Blog Post", "Launch notes v2"]),
	tool("timestamp", "Timestamp", "Engineering", "Random timestamp records.", "Range", false, "2020-2030", "fields", "Generate timestamp", ["2020-2030", "unix seconds"], [
		field("start", "Start", "2020-01-01T00:00:00Z", true),
		field("end", "End", "2030-12-31T23:59:59Z", true),
		field("unit", "Unit", "seconds", false, "select", ["seconds", "milliseconds"]),
		field("count", "Count", "1", true),
	]),
	tool("date", "Date", "Engineering", "Random dates in multiple formats.", "Range", false, "1970-01-01", "text", "Generate date", ["2020-01-01", "unix"], [
		field("startDate", "Start date", "1970-01-01", true),
		field("endDate", "End date", todayIsoDate(), true),
		field("format", "Format", "iso8601", false, "select", ["iso8601", "us", "eu", "long", "short", "unix"]),
		field("count", "Count", "10", true),
	]),
	tool("time", "Time", "Engineering", "Random times with hour range and second controls.", "Format", false, "24-hour", "fields", "Generate time", ["24-hour", "12-hour"], [
		field("format", "Format", "24-hour", false, "select", ["24-hour", "12-hour"]),
		field("startHour", "Start hour", "0", true),
		field("endHour", "End hour", "23", true),
		field("includeSeconds", "Include seconds", "true", false, "select", ["true", "false"]),
		field("count", "Count", "1", true),
	]),
	tool("datetime", "Timestamp", "Engineering", "Random Unix or ISO 8601 timestamps.", "Format", false, "unix", "fields", "Generate timestamp", ["unix", "iso8601"], [
		field("format", "Format", "unix", false, "select", ["unix", "iso8601"]),
		field("startDate", "Start date", "1970-01-01", true),
		field("endDate", "End date", todayIsoDate(), true),
		field("count", "Count", "1", true),
	]),
	tool("ip-address", "IP address", "Identifiers", "Random IPv4 and IPv6 addresses with uniqueness and range controls.", "Version", false, "ipv4", "text", "Generate IP", ["ipv4", "ipv6"], [
		field("version", "Version", "ipv4", false, "select", ["ipv4", "ipv6", "both"]),
		field("count", "Count", "10", true),
		field("unique", "Unique", "false", false, "select", ["false", "true"]),
		field("includePrivate", "Private ranges", "true", false, "select", ["true", "false"]),
		field("includeLocalhost", "Localhost", "false", false, "select", ["false", "true"]),
	]),
	tool("ipv4", "IPv4 address", "Identifiers", "Random IPv4 addresses.", "Count", false, "10", "text", "Generate IPv4", ["10", "25"], [
		field("count", "Count", "10", true),
		field("unique", "Unique", "false", false, "select", ["false", "true"]),
		field("includePrivate", "Private ranges", "true", false, "select", ["true", "false"]),
		field("includeLocalhost", "Localhost", "false", false, "select", ["false", "true"]),
	]),
	tool("ipv6", "IPv6 address", "Identifiers", "Random IPv6 addresses.", "Count", false, "10", "text", "Generate IPv6", ["10", "25"], [
		field("count", "Count", "10", true),
		field("unique", "Unique", "false", false, "select", ["false", "true"]),
		field("includePrivate", "Private ranges", "true", false, "select", ["true", "false"]),
		field("includeLocalhost", "Localhost", "false", false, "select", ["false", "true"]),
	]),
	tool("mac", "MAC address", "Identifiers", "IEEE 802 MAC addresses with format and address-bit controls.", "Format", false, "colon", "text", "Generate MAC", ["colon", "cisco"], [
		field("format", "Format", "colon", false, "select", ["colon", "hyphen", "dot", "cisco", "plain"]),
		field("count", "Count", "10", true),
		field("uppercase", "Uppercase", "false", false, "select", ["false", "true"]),
		field("local", "Locally administered", "true", false, "select", ["true", "false"]),
		field("unicast", "Unicast", "true", false, "select", ["true", "false"]),
		field("unique", "Unique", "false", false, "select", ["false", "true"]),
	]),
	tool("phone", "Phone number", "Identifiers", "Random country-specific test phone numbers.", "Country", false, "US", "text", "Generate phone", ["US", "GB"], [
		field("country", "Country", "US", false, "select", ["US", "CA", "GB", "DE", "FR", "ES", "IT", "NL", "AU", "JP", "CN", "IN", "BR", "MX"]),
		field("format", "Format", "national", false, "select", ["national", "international", "e164"]),
		field("count", "Count", "10", true),
		field("unique", "Unique", "false", false, "select", ["false", "true"]),
	]),
	tool("username", "Username", "Identifiers", "Random usernames with style, length, and uniqueness controls.", "Style", false, "mixed", "text", "Generate username", ["mixed", "gamer"], [
		field("style", "Style", "mixed", false, "select", ["professional", "gamer", "quirky", "simple", "cool", "mixed"]),
		field("count", "Count", "10", true),
		field("minLength", "Min length", "6", true),
		field("maxLength", "Max length", "15", true),
		field("includeNumbers", "Include numbers", "true", false, "select", ["true", "false"]),
		field("unique", "Unique", "true", false, "select", ["true", "false"]),
	]),
	tool("company", "Company name", "Identifiers", "Random company names by style and industry.", "Style", false, "mixed", "text", "Generate company", ["mixed", "tech"], [
		field("style", "Style", "mixed", false, "select", ["professional", "creative", "modern", "traditional", "tech", "mixed"]),
		field("industry", "Industry", "general", false, "select", ["general", "tech", "finance", "retail", "healthcare", "consulting", "food", "fashion", "construction", "education"]),
		field("count", "Count", "10", true),
	]),
	tool("minecraft-uuid", "Minecraft UUID", "Identifiers", "Random Minecraft UUID formats.", "Count", false, "1", "fields", "Generate UUID", ["1", "10"], [
		field("count", "Count", "1", true),
	]),
	tool("us-state", "US state", "Geographic", "Random US states.", "Count", false, "1", "text", "Generate state", ["1", "5"], [
		field("count", "Count", "1", true),
	]),
	tool("zodiac", "Zodiac sign", "Identifiers", "Random zodiac signs.", "Count", false, "1", "text", "Generate sign", ["1", "5"], [
		field("count", "Count", "1", true),
	]),
	tool("person", "Person", "People", "Generated fictional identities with optional financial and professional data.", "Locale", false, "en_GB", "fields", "Generate person", ["en_GB", "en_US", "de_DE"], [
		field("locale", "Locale", "en_GB", false, "select", ["en_GB", "en_US", "fr_FR", "es_ES", "it_IT", "de_DE", "pt_PT", "nl_NL", "pl_PL"]),
		field("count", "Count", "1", true),
		field("gender", "Gender", "mixed", false, "select", ["mixed", "male", "female"]),
		field("ageMin", "Min age", "18", true),
		field("ageMax", "Max age", "80", true),
		field("includeFinancial", "Financial data", "true", false, "select", ["true", "false"]),
		field("includeProfessional", "Professional data", "true", false, "select", ["true", "false"]),
	]),
	tool("number", "Number", "Random", "Random numbers by type, range, and precision.", "Type", false, "integer", "text", "Generate number", ["integer", "negative", "even", "odd", "prime", "percentage"], [
		field("min", "Min", "1", true),
		field("max", "Max", "100", true),
		field("type", "Type", "integer", true, "select", ["integer", "decimal", "prime", "percentage", "even", "odd", "negative"]),
		field("decimals", "Decimals", "2", true),
		field("count", "Count", "10", true),
	]),
	tool("binary", "Binary number", "Random", "Random binary values with configurable bit width and count.", "Bits", false, "8", "text", "Generate binary", ["8", "16"], [
		field("bits", "Bits", "8", true),
		field("count", "Count", "10", true),
	]),
	tool("hex-number", "Hex number", "Random", "Random hexadecimal numbers with length and format controls.", "Length", false, "8", "text", "Generate hex", ["8", "16"], [
		field("count", "Count", "10", true),
		field("length", "Length", "8", true),
		field("prefix", "0x prefix", "true", false, "select", ["true", "false"]),
		field("uppercase", "Uppercase", "true", false, "select", ["true", "false"]),
		field("unique", "Unique", "false", false, "select", ["false", "true"]),
	]),
	tool("octal-number", "Octal number", "Random", "Random octal numbers with length and prefix controls.", "Length", false, "8", "text", "Generate octal", ["8", "16"], [
		field("count", "Count", "10", true),
		field("length", "Length", "8", true),
		field("prefix", "0o prefix", "true", false, "select", ["true", "false"]),
		field("unique", "Unique", "false", false, "select", ["false", "true"]),
	]),
	tool("fraction", "Fraction", "Random", "Random fraction records.", "Type", false, "proper", "fields", "Generate fraction", ["proper", "mixed"], [
		field("type", "Type", "proper", true, "select", ["proper", "improper", "mixed"]),
		field("maxNumerator", "Max numerator", "12", true),
		field("maxDenominator", "Max denominator", "12", true),
		field("simplify", "Simplify", "yes", false, "select", ["yes", "no"]),
		field("count", "Count", "1", true),
	]),
	tool("string", "String", "Strings", "Random strings, words, sentences, binary, hex, and base64.", "Length", false, "32", "text", "Generate string", ["alphanumeric", "lorem"], [
		field("type", "Type", "alphanumeric", false, "select", ["alphanumeric", "letters", "words", "sentences", "paragraphs", "binary", "hex", "base64", "lorem"]),
		field("count", "Count", "1", true),
		field("length", "Length", "32", true),
		field("wordCount", "Words", "5", true),
		field("sentenceCount", "Sentences", "3", true),
		field("paragraphCount", "Paragraphs", "2", true),
		field("byteCount", "Bytes", "32", true),
		field("case", "Case", "mixed", false, "select", ["mixed", "lower", "upper"]),
		field("uppercase", "Uppercase", "true", false, "select", ["true", "false"]),
		field("lowercase", "Lowercase", "true", false, "select", ["true", "false"]),
		field("numbers", "Numbers", "true", false, "select", ["true", "false"]),
	]),
	tool("emoji", "Emoji", "Strings", "Random emoji string.", "Count", false, "6", "text", "Generate emoji", ["6", "12"], [
		field("count", "Count", "6", true),
		field("separator", "Separator", "", false),
	]),
	tool("pin", "PIN code", "Security", "Numeric PINs with pattern filters.", "Length", false, "4", "text", "Generate PIN", ["4", "6"], [
		field("length", "Length", "4", true),
		field("count", "Count", "10", true),
		field("uniqueDigits", "Unique digits", "false", false, "select", ["false", "true"]),
		field("excludeSequential", "Exclude sequential", "false", false, "select", ["false", "true"]),
		field("excludeRepeating", "Exclude repeating", "false", false, "select", ["false", "true"]),
	]),
	tool("passphrase", "Passphrase", "Security", "Memorable passphrases with word and suffix controls.", "Words", false, "5", "text", "Generate phrase", ["5", "6"], [
		field("wordCount", "Words", "5", true),
		field("separator", "Separator", "-", false),
		field("count", "Count", "5", true),
		field("capitalize", "Capitalize", "false", false, "select", ["false", "true"]),
		field("includeNumbers", "Include number", "false", false, "select", ["false", "true"]),
	]),
	tool("colour", "Colour", "Design", "Random colours with formats and contrast checks.", "Count", false, "10", "fields", "Generate colours", ["5", "10"], [
		field("count", "Count", "10", true),
		field("format", "Format", "hex", false, "select", ["hex", "rgb", "hsl", "rgba", "hsla", "all"]),
		field("palette", "Palette", "random", false, "select", ["random", "pastel", "vibrant", "dark", "light", "grayscale"]),
		field("alpha", "Alpha", "1", true),
	]),
	tool("palette", "Palette", "Design", "Configurable colour palette with harmony controls.", "Seed", false, "Cyber citrus checkout", "palette", "Make palette", ["Cyber citrus checkout", "Neon ink docs"], [
		field("seed", "Seed", "Cyber citrus checkout", false),
		field("count", "Count", "5", true),
		field("harmony", "Harmony", "analogous", false, "select", ["analogous", "complementary", "triadic", "split", "monochrome", "random"]),
		field("saturation", "Saturation", "72", true),
		field("lightness", "Lightness", "52", true),
	]),
	tool("lorem", "Lorem ipsum", "Design", "Placeholder copy with configurable length.", "Topic", false, "Pashi interface", "text", "Generate lorem", ["Pashi interface", "Checkout flow"], [
		field("topic", "Topic", "Pashi interface", false),
		field("paragraphs", "Paragraphs", "2", true),
		field("sentences", "Sentences each", "3", true),
	]),
	tool("utm", "UTM link", "Product", "Campaign URL with UTM tags.", "URL", false, "https://nicholasgriffin.dev/pricing", "text", "Build UTM", ["https://nicholasgriffin.dev/pricing", "https://pashi.app"], [
		field("url", "URL", "https://example.com/pricing", true),
		field("source", "Source", "newsletter", true),
		field("medium", "Medium", "email", true),
		field("campaign", "Campaign", "launch", true),
	]),
	tool("coordinates", "Coordinates", "Geographic", "Random coordinates with region, format, and custom bounds.", "Region", false, "global", "fields", "Generate coords", ["global", "uk"], [
		field("region", "Region", "global", false, "select", ["global", "north-america", "south-america", "europe", "africa", "asia", "oceania", "usa", "canada", "uk", "australia"]),
		field("count", "Count", "1", true),
		field("format", "Format", "decimal", false, "select", ["decimal", "dms", "dm"]),
		field("precision", "Precision", "6", true),
		field("minLat", "Min latitude", "", false),
		field("maxLat", "Max latitude", "", false),
		field("minLon", "Min longitude", "", false),
		field("maxLon", "Max longitude", "", false),
	]),
	tool("zip", "Post code", "Geographic", "Random post codes for multiple locales.", "Locale", false, "en_GB", "text", "Generate post code", ["en_GB", "en_US"], [
		field("locale", "Locale", "en_GB", false, "select", [
			"en_GB",
			"en_US",
			"en_CA",
			"pt_BR",
			"es_AR",
			"fr_FR",
			"de_DE",
			"es_ES",
			"it_IT",
			"pt_PT",
			"nl_NL",
			"pl_PL",
			"ru_RU",
			"tr_TR",
			"uk_UA",
			"en_IN",
			"bn_BD",
			"ja_JP",
			"zh_CN",
			"zh_TW",
			"ko_KR",
			"id_ID",
			"th_TH",
			"vi_VN",
			"fa_IR",
			"ar_SA",
			"ar_EG",
			"en_AU",
		]),
		field("count", "Count", "10", true),
	]),
	tool("card", "Card number", "TestData", "Brand-valid, Luhn-valid test card details.", "Type", false, "visa", "fields", "Generate card", ["visa", "mastercard"], [
		field("type", "Type", "visa", false, "select", ["visa", "mastercard", "amex", "discover"]),
		field("count", "Count", "1", true),
		field("includeDetails", "Include details", "true", false, "select", ["true", "false"]),
		field("includeName", "Include name", "true", false, "select", ["true", "false"]),
	]),
	tool("iban", "IBAN", "TestData", "Valid-checksum IBANs for selected countries.", "Country", false, "GB", "text", "Generate IBAN", ["GB", "DE"], [
		field("country", "Country", "GB", false, "select", ["GB", "DE", "FR", "IT", "ES", "NL"]),
		field("count", "Count", "10", true),
	]),
	tool("dice", "Dice", "Gaming", "Roll RPG dice with drop, keep, modifier, and bulk controls.", "Dice type", false, "d6", "fields", "Roll dice", ["d20", "4d6", "2d20"], [
		field("count", "Rolls", "1", true),
		field("dice_type", "Dice type", "d6", false, "select", ["d4", "d6", "d8", "d10", "d12", "d20", "d100", "custom"]),
		field("dice_sides", "Custom sides", "6", true),
		field("num_dice", "Dice count", "1", true),
		field("modifier", "Modifier", "0", true),
		field("drop_lowest", "Drop lowest", "0", true),
		field("drop_highest", "Drop highest", "0", true),
		field("keep_highest", "Keep highest", "0", true),
		field("show_individual", "Show rolls", "true", false, "select", ["true", "false"]),
	]),
	tool("dice-probability", "Dice probability", "Gaming", "Exact probability for dice notation and target.", "Notation", false, "2d6", "fields", "Calculate odds", ["2d6 >= 7", "4d6 drop lowest >= 12"], [
		field("notation", "Notation", "2d6", true),
		field("comparison", "Comparison", ">=", true, "select", [">=", ">", "=", "<=", "<"]),
		field("target", "Target", "7", true),
	]),
	tool("lottery", "Lottery", "Gaming", "Lottery numbers from a configurable range.", "Count", false, "6", "fields", "Generate lottery", ["6 from 1-59"], [
		field("count", "Count", "6", true),
		field("min", "Min", "1", true),
		field("max", "Max", "59", true),
	]),
	tool("minecraft-seed", "Minecraft seed", "Gaming", "Random signed 64-bit Minecraft seed.", "Input", false, "", "text", "Generate seed", ["world seed"]),
	tool("pokemon", "Pokemon", "Gaming", "Random Kanto Pokedex entries with type filtering.", "Type", false, "any", "text", "Generate Pokemon", ["any", "electric"], [
		field("type", "Type", "any", false, "select", POKEMON_TYPES),
		field("count", "Count", "1", true),
	]),
	tool("coinflip", "Coin flip", "Gaming", "Independent CSPRNG HEADS or TAILS flips.", "Count", false, "1", "text", "Flip coin", ["1", "10"], [
		field("count", "Count", "1", true),
	]),
	tool("list-randomizer", "List randomizer", "Tools", "Shuffle a comma or newline list.", "Items", true, "Ada\nGrace\nMargaret", "text", "Shuffle list", ["Ada, Grace, Margaret"], [
		field("items", "Items", "Ada\nGrace\nMargaret", true, "textarea"),
	]),
	tool("yes-no", "Yes or no", "Tools", "Weighted yes/no decision.", "Chance", false, "50", "text", "Decide", ["50"], [
		field("yesWeight", "Yes chance", "50", true),
	]),
	tool("teams", "Teams", "Tools", "Split a list into balanced random teams.", "Items", true, "Ada\nGrace\nMargaret\nKatherine", "fields", "Make teams", ["Ada, Grace, Margaret, Katherine"], [
		field("items", "Items", "Ada\nGrace\nMargaret\nKatherine", true, "textarea"),
		field("teams", "Teams", "2", true),
	]),
	tool("secret-santa", "Secret Santa", "Tools", "Assign each person a different recipient.", "People", true, "Ada\nGrace\nMargaret", "fields", "Assign pairs", ["Ada, Grace, Margaret"], [
		field("items", "People", "Ada\nGrace\nMargaret", true, "textarea"),
	]),
	tool("name-picker", "Name picker", "Tools", "Pick one item from a comma or newline list.", "Items", true, "Ada\nGrace\nMargaret", "text", "Pick one", ["Ada, Grace, Margaret"], [
		field("items", "Items", "Ada\nGrace\nMargaret", true, "textarea"),
	]),
	];
}

export function findGenerator(type: string) {
	const normalisedType = type.trim().toLowerCase();
	return createGeneratorTools().find((generator) =>
		generator.id === normalisedType || generator.aliases.includes(normalisedType),
	);
}

export function listGeneratorTools() {
	return createGeneratorTools();
}

function tool(
	id: string,
	label: string,
	audience: Audience,
	description: string,
	inputLabel: string,
	required: boolean,
	placeholder: string,
	resultKind: ResultKind,
	actionLabel: string,
	examples: readonly string[],
	fields?: readonly GeneratorInputField[],
): GeneratorTool {
	return {
		aliases: GENERATOR_ALIASES[id] ?? [],
		audience,
		description,
		display: {
			actionLabel,
			category: CATEGORY_LABELS[audience],
			examples,
		},
		endpoint: `/api/${id}`,
		id,
		input: {
			fields,
			label: inputLabel,
			mode: NO_INPUT_TOOL_IDS.has(id) ? "none" : "text",
			required,
		},
		label,
		modes: resultKind === "image" ? [] : ["ai"],
		placeholder,
		result: { kind: resultKind },
	};
}

function field(
	id: string,
	label: string,
	placeholder: string,
	required: boolean,
	type: GeneratorInputField["type"] = "text",
	options?: readonly string[],
): GeneratorInputField {
	return { id, label, options, placeholder, required, type };
}
