import type { ConverterTool } from "./types";
import { TEXT_FILE_FORMATS } from "./text-file-conversion.ts";
import { TEXT_TRANSFORM_FORMATS } from "../../utils/text-transforms.ts";
import { UNIT_OUTPUTS } from "../../utils/unit-conversion.ts";
import { HTML_TRANSFORM_FORMATS } from "./html-transform.ts";
import { JSON_TRANSFORM_FORMATS } from "./json-transform.ts";
import { MARKDOWN_TARGET_FORMATS } from "./markdown-targets.ts";
import { TIMESTAMP_TRANSFORM_FORMATS } from "./timestamp-transform.ts";
import { URL_TRANSFORM_FORMATS } from "./url-transform.ts";

const TEXT_REQUEST_FORMATS = [
	"application/json",
	"application/x-www-form-urlencoded",
	"text/plain",
] as const;
const IMAGE_REQUEST_FORMATS = [
	"application/json",
	"application/x-www-form-urlencoded",
	"application/octet-stream",
	"image/*",
	"image/avif",
	"image/bmp",
	"image/gif",
	"image/jpeg",
	"image/png",
	"image/tiff",
	"image/webp",
	"multipart/form-data",
	"text/plain",
] as const;
const AUDIO_REQUEST_FORMATS = [
	"application/octet-stream",
	"audio/*",
	"audio/aac",
	"audio/flac",
	"audio/mpeg",
	"audio/ogg",
	"audio/wav",
	"multipart/form-data",
] as const;
const VIDEO_REQUEST_FORMATS = [
	"audio/*",
	"application/octet-stream",
	"multipart/form-data",
	"video/*",
	"video/avi",
	"video/mpeg",
	"video/mp4",
	"video/quicktime",
	"video/webm",
] as const;
const FILE_REQUEST_FORMATS = [
	"application/json",
	"application/sql",
	"application/x-www-form-urlencoded",
	"application/xml",
	"application/yaml",
	"multipart/form-data",
	"text/csv",
	"text/html",
	"text/markdown",
	"text/plain",
] as const;
const DOCUMENT_REQUEST_FORMATS = [
	"application/epub+zip",
	"application/msword",
	"application/octet-stream",
	"application/rtf",
	"application/vnd.oasis.opendocument.text",
	"application/vnd.openxmlformats-officedocument.wordprocessingml.document",
	"multipart/form-data",
	"text/html",
	"text/markdown",
	"text/plain",
] as const;

const CONVERTER_TOOLS: readonly ConverterTool[] = [
	{
		aliases: ["md-to-jira", "markdown-to-confluence", "md-to-confluence"],
		api: {
			accepts: TEXT_REQUEST_FORMATS,
			examples: [
				{
					body: "## Heading\n\n- **Bold** item",
					contentType: "text/markdown",
					description: "Post Markdown as the raw request body.",
					method: "POST",
					url: "/api/markdown-to-jira",
				},
				{
					description: "Convert Markdown supplied in the query string.",
					method: "GET",
					url: "/api/markdown-to-jira?input=%23%23%20Heading",
				},
			],
			fields: [],
			methods: ["GET", "POST"],
			response: "json",
		},
		audience: "Documents",
		description: "Convert Markdown into Jira and Confluence wiki markup.",
		display: {
			actionLabel: "Convert to Jira",
			category: "Jira and Confluence",
			examples: [
				"## Release notes\n\n- **Fixed** auth\n- Added `copy` action",
				"[Pashi](https://pashi.app) is **fast**",
			],
		},
		endpoint: "/api/markdown-to-jira",
		id: "markdown-to-jira",
		input: {
			label: "Markdown",
			kind: "text",
			required: true,
		},
		label: "Markdown to Jira",
		outputs: ["jira", "confluence"],
		placeholder: "## Heading\n\n- **Bold** item\n- [Link](https://pashi.app)",
		runtime: "worker",
		status: "available",
	},
	{
		aliases: ["jira-to-md", "confluence-to-markdown", "confluence-to-md"],
		api: {
			accepts: TEXT_REQUEST_FORMATS,
			examples: [
				{
					body: "h2. Heading\n\n* *Bold* item",
					contentType: "text/plain",
					description: "Post Jira markup as the raw request body.",
					method: "POST",
					url: "/api/jira-to-markdown",
				},
			],
			fields: [],
			methods: ["GET", "POST"],
			response: "json",
		},
		audience: "Documents",
		description: "Convert Jira and Confluence wiki markup back into Markdown.",
		display: {
			actionLabel: "Convert to Markdown",
			category: "Jira and Confluence",
			examples: [
				"h2. Release notes\n\n* *Fixed* auth\n* Added {{copy}} action",
				"[Pashi|https://pashi.app] is *fast*",
			],
		},
		endpoint: "/api/jira-to-markdown",
		id: "jira-to-markdown",
		input: {
			label: "Jira markup",
			kind: "text",
			required: true,
		},
		label: "Jira to Markdown",
		outputs: ["markdown"],
		placeholder: "h2. Heading\n\n* *Bold* item\n* [Link|https://pashi.app]",
		runtime: "worker",
		status: "available",
	},
	{
		aliases: [
			"markdown-format",
			"markdown-to-slack-converter",
			"markdown-to-html-converter",
			"markdown-to-wordpress-html-converter",
			"markdown-link-generator",
			"markdown-image-syntax-generator",
			"markdown-task-list-generator",
		],
		api: {
			accepts: TEXT_REQUEST_FORMATS,
			examples: [
				{
					body: "## Release notes\n\n- **Fixed** auth",
					contentType: "text/markdown",
					description: "Post Markdown and select a target output format.",
					method: "POST",
					url: "/api/markdown-format?outputFormat=slack",
				},
			],
			fields: [
				{
					description: "Target Markdown publishing format.",
					id: "outputFormat",
					required: true,
					values: MARKDOWN_TARGET_FORMATS,
				},
			],
			methods: ["GET", "POST"],
			response: "json",
		},
		audience: "Documents",
		description: "Convert Markdown into Slack-friendly text or WordPress HTML.",
		display: {
			actionLabel: "Convert Markdown",
			category: "Markdown",
			examples: [
				"## Release notes\n\n- **Fixed** auth\n- [Pashi](https://pashi.app)",
			],
		},
		endpoint: "/api/markdown-format",
		id: "markdown-format",
		input: {
			label: "Markdown",
			kind: "text",
			required: true,
		},
		label: "Markdown targets",
		outputs: MARKDOWN_TARGET_FORMATS,
		placeholder: "## Heading\n\n- **Bold** item",
		runtime: "worker",
		status: "available",
	},
	{
		aliases: [
			"html-entity-encoder-decoder",
			"html-escape-unescape",
			"html-tag-remover-stripper",
			"html-link-extractor-checker",
			"html-comment-remover-extractor",
			"html-to-markdown-converter",
		],
		api: {
			accepts: TEXT_REQUEST_FORMATS,
			examples: [
				{
					body: "<h1>Title</h1><p>Hello <strong>world</strong>.</p>",
					contentType: "text/html",
					description: "Post HTML and select a transform with outputFormat.",
					method: "POST",
					url: "/api/html-transform?outputFormat=to-markdown",
				},
			],
			fields: [
				{
					description: "HTML transform mode.",
					id: "outputFormat",
					required: true,
					values: HTML_TRANSFORM_FORMATS,
				},
			],
			methods: ["GET", "POST"],
			response: "json",
		},
		audience: "Documents",
		description: "Escape, unescape, strip, inspect, and convert simple HTML snippets to Markdown.",
		display: {
			actionLabel: "Transform HTML",
			category: "HTML",
			examples: [
				"<h1>Title</h1><p>Hello <strong>world</strong>.</p>",
			],
		},
		endpoint: "/api/html-transform",
		id: "html-transform",
		input: {
			label: "HTML",
			kind: "text",
			required: true,
		},
		label: "HTML transform",
		outputs: HTML_TRANSFORM_FORMATS,
		placeholder: "<p>Hello <strong>world</strong>.</p>",
		runtime: "worker",
		status: "available",
	},
	{
		aliases: [
			"unix-timestamp-converter",
			"milliseconds-timestamp-converter",
			"human-date-to-timestamp",
			"timestamp-to-readable-date",
			"iso-8601-timestamp-converter",
			"rfc-timestamp-converter",
			"discord-timestamp-generator",
			"add-subtract-time-timestamp",
			"timestamp-difference-calculator",
			"timestamp-validator-formatter",
			"epoch-timestamp-generator",
		],
		api: {
			accepts: TEXT_REQUEST_FORMATS,
			examples: [
				{
					body: "2024-01-02T03:04:05Z",
					contentType: "text/plain",
					description: "Post a timestamp or date and select an output format.",
					method: "POST",
					url: "/api/timestamp-transform?outputFormat=unix",
				},
			],
			fields: [
				{
					description: "Timestamp output or calculation mode.",
					id: "outputFormat",
					required: true,
					values: TIMESTAMP_TRANSFORM_FORMATS,
				},
				{
					description: "Amount for add or subtract modes.",
					id: "amount",
				},
				{
					description: "Unit for add or subtract modes.",
					id: "unit",
					values: ["milliseconds", "seconds", "minutes", "hours", "days", "weeks"],
				},
				{
					description: "End timestamp for difference mode.",
					id: "until",
				},
				{
					description: "Discord timestamp style.",
					id: "style",
					values: ["shortTime", "longTime", "shortDate", "longDate", "full", "relative"],
				},
			],
			methods: ["GET", "POST"],
			response: "json",
		},
		audience: "Documents",
		description: "Convert timestamps and dates between Unix, milliseconds, ISO, readable UTC, RFC, Discord, and simple date math outputs.",
		display: {
			actionLabel: "Convert timestamp",
			category: "Dates",
			examples: [
				"2024-01-02T03:04:05Z",
				"1704164645",
			],
		},
		endpoint: "/api/timestamp-transform",
		id: "timestamp-transform",
		input: {
			label: "Timestamp or date",
			kind: "text",
			required: true,
		},
		label: "Timestamp transform",
		outputs: TIMESTAMP_TRANSFORM_FORMATS,
		placeholder: "2024-01-02T03:04:05Z",
		runtime: "worker",
		status: "available",
	},
	{
		aliases: [
			"text-transform",
			"character-counter",
			"case-converter",
			"duplicate-word-remover",
			"find-and-replace-text",
			"remove-duplicate-lines",
			"sentence-counter",
			"string-length-calculator",
			"string-reverse",
			"text-case-converter",
			"leet-speak-converter",
			"text-line-sorter",
			"text-repeater",
			"text-reverser",
			"text-size-calculator",
			"text-to-hashtags-generator",
			"text-to-list-converter",
			"upside-down-text-generator",
			"text-to-binary-converter",
			"binary-to-text-converter",
			"text-to-hex-converter",
			"hex-to-text-converter",
			"ascii-to-decimal-converter",
			"ascii-to-hex-converter",
			"ascii-to-octal-converter",
			"binary-decimal-hex-converter",
			"url-decoder",
			"url-encoder",
			"url-case-converter",
			"unicode-escape-encoder",
			"unicode-normalizer",
			"unicode-text-converter",
			"unicode-url-encoder",
			"unicode-whitespace-remover",
			"unicode-zero-width-tool",
			"vertical-text-generator",
			"whitespace-remover",
			"word-counter",
			"word-counter-character-counter",
			"word-frequency-counter",
		],
		api: {
			accepts: TEXT_REQUEST_FORMATS,
			examples: [
				{
					body: "Hello, Pashi App!",
					contentType: "text/plain",
					description: "Post text and select a transform with outputFormat.",
					method: "POST",
					url: "/api/text-transform?outputFormat=kebab",
				},
				{
					description: "Decode a binary byte sequence.",
					method: "GET",
					url: "/api/text-transform?input=01001000%2001101001&outputFormat=from-binary",
				},
			],
			fields: [
				{
					description: "Text transform or encoding mode.",
					id: "outputFormat",
					required: true,
					values: TEXT_TRANSFORM_FORMATS,
				},
				{
					description: "Repeat count for repeat mode.",
					id: "count",
				},
				{
					description: "Search text for replace mode.",
					id: "search",
				},
				{
					description: "Replacement text for replace mode.",
					id: "replace",
				},
			],
			methods: ["GET", "POST"],
			response: "json",
		},
		audience: "Documents",
		description: "Convert case, encode, decode, count, sort, dedupe, and reshape text.",
		display: {
			actionLabel: "Transform text",
			category: "Text",
			examples: [
				"Hello, Pashi App!",
				"01001000 01101001",
			],
		},
		endpoint: "/api/text-transform",
		id: "text-transform",
		input: {
			label: "Text",
			kind: "text",
			required: true,
		},
		label: "Text and encoding",
		outputs: TEXT_TRANSFORM_FORMATS,
		placeholder: "Hello, Pashi App!",
		runtime: "worker",
		status: "available",
	},
	{
		aliases: [
			"json-formatter-beautifier",
			"json-pretty-print",
			"json-minifier",
			"json-sorter",
			"json-flatten",
			"json-key-extractor",
			"json-key-value-extractor",
			"json-base64",
			"json-encode-decode",
			"json-escape-unescape",
			"json-stringify-parse",
		],
		api: {
			accepts: TEXT_REQUEST_FORMATS,
			examples: [
				{
					body: "{\"b\":2,\"a\":1}",
					contentType: "application/json",
					description: "Post JSON and select a transform with outputFormat.",
					method: "POST",
					url: "/api/json-transform?outputFormat=format",
				},
			],
			fields: [
				{
					description: "JSON transform mode.",
					id: "outputFormat",
					required: true,
					values: JSON_TRANSFORM_FORMATS,
				},
			],
			methods: ["GET", "POST"],
			response: "json",
		},
		audience: "Documents",
		description: "Format, minify, sort, flatten, inspect, encode, and escape JSON text.",
		display: {
			actionLabel: "Transform JSON",
			category: "JSON",
			examples: [
				"{\"b\":2,\"a\":{\"c\":3}}",
			],
		},
		endpoint: "/api/json-transform",
		id: "json-transform",
		input: {
			label: "JSON",
			kind: "text",
			required: true,
		},
		label: "JSON transform",
		outputs: JSON_TRANSFORM_FORMATS,
		placeholder: "{\"b\":2,\"a\":{\"c\":3}}",
		runtime: "worker",
		status: "available",
	},
	{
		aliases: [
			"url-parser",
			"url-query-string-extractor",
			"url-email-link-extractor",
			"url-duplicate-finder",
		],
		api: {
			accepts: TEXT_REQUEST_FORMATS,
			examples: [
				{
					body: "https://example.com/search?q=pashi&tag=tools",
					contentType: "text/plain",
					description: "Post a URL or text containing URLs and choose a transform with outputFormat.",
					method: "POST",
					url: "/api/url-transform?outputFormat=parse",
				},
			],
			fields: [
				{
					description: "URL inspection or extraction mode.",
					id: "outputFormat",
					required: true,
					values: URL_TRANSFORM_FORMATS,
				},
			],
			methods: ["GET", "POST"],
			response: "json",
		},
		audience: "Documents",
		description: "Parse URLs, extract query parameters, pull links and email addresses from text, and deduplicate links.",
		display: {
			actionLabel: "Inspect URL",
			category: "URLs",
			examples: [
				"https://example.com/search?q=pashi&tag=tools",
				"Email hello@example.com or read https://pashi.app",
			],
		},
		endpoint: "/api/url-transform",
		id: "url-transform",
		input: {
			label: "URL or text",
			kind: "text",
			required: true,
		},
		label: "URL transform",
		outputs: URL_TRANSFORM_FORMATS,
		placeholder: "https://example.com/search?q=pashi&tag=tools",
		runtime: "worker",
		status: "available",
	},
	{
		aliases: [
			"unit-converter",
			"unit-converter-tool",
			"length-converter",
			"area-converter",
			"volume-converter",
			"weight-converter",
			"weight-and-mass",
			"temperature-converter",
			"speed-converter",
			"data-storage-converter",
			"degrees-radians-converter",
			"time-converter",
			"pressure-converter",
			"energy-converter",
			"power",
			"power-converter",
			"force",
			"force-converter",
			"frequency",
			"frequency-converter",
			"torque",
			"torque-converter",
			"moment-of-force",
		],
		api: {
			accepts: TEXT_REQUEST_FORMATS,
			examples: [
				{
					body: "10 m",
					contentType: "text/plain",
					description: "Convert a value with a source unit into the selected output unit.",
					method: "POST",
					url: "/api/unit-converter?outputFormat=ft",
				},
				{
					description: "Convert Celsius to Fahrenheit.",
					method: "GET",
					url: "/api/unit-converter?input=100%20c&outputFormat=f",
				},
			],
			fields: [
				{
					description: "Target unit.",
					id: "outputFormat",
					required: true,
					values: UNIT_OUTPUTS,
				},
				{
					description: "Optional source unit when the input contains only a number.",
					id: "fromUnit",
				},
			],
			methods: ["GET", "POST"],
			response: "json",
		},
		audience: "Documents",
		description: "Convert common length, mass, temperature, data, speed, area, volume, angle, time, pressure, energy, power, force, frequency, and torque units.",
		display: {
			actionLabel: "Convert unit",
			category: "Units",
			examples: [
				"10 m",
				"100 c",
				"1048576 b",
			],
		},
		endpoint: "/api/unit-converter",
		id: "unit-converter",
		input: {
			label: "Value with unit",
			kind: "text",
			required: true,
		},
		label: "Unit converter",
		outputs: UNIT_OUTPUTS,
		placeholder: "10 m",
		runtime: "worker",
		status: "available",
	},
	{
		aliases: [
			"image-format",
			"image-transcode",
			"image-url",
			"remote-image",
			"png-to-webp",
			"jpg-to-webp",
			"svg-to-png-converter",
			"svg-to-jpg-converter",
			"svg-to-webp-converter",
			"svg-to-ico-converter",
			"favicon-generator-from-image",
			"icon-file-format-converter-all-types",
			"animated-gif-to-icon-converter",
		],
		api: {
			accepts: IMAGE_REQUEST_FORMATS,
			examples: [
				{
					description: "Fetch and convert a public image URL to WebP.",
					method: "GET",
					url: "/api/image-format?input=https%3A%2F%2Fnicholasgriffin.dev%2Favatar.png&outputFormat=webp",
				},
				{
					body: "file=@image.png; outputFormat=avif",
					contentType: "multipart/form-data",
					description: "Upload an image file and create a conversion job.",
					method: "POST",
					url: "/api/image-format",
				},
				{
					description: "Check a queued image conversion job.",
					method: "GET",
					url: "/api/image-format?job=<job-id>",
				},
			],
			fields: [
				{
					description: "Target image format.",
					id: "outputFormat",
					values: ["webp", "jpeg", "png", "avif", "gif", "bmp", "tiff", "ico", "mjpeg"],
				},
				{
					description: "Optional image quality from 1 to 100.",
					id: "quality",
				},
			],
			methods: ["GET", "POST"],
			response: "json",
		},
		audience: "Media",
		description: "Convert image URLs immediately, or upload image files into the async ffmpeg pipeline.",
		display: {
			actionLabel: "Convert image",
			category: "Media",
			examples: [],
		},
		endpoint: "/api/image-format",
		id: "image-format",
		input: {
			accept: ["image/*", ".avif", ".bmp", ".gif", ".ico", ".jpg", ".jpeg", ".mjpeg", ".png", ".tif", ".tiff", ".webp"],
			label: "Image file",
			kind: "file",
			required: true,
		},
		label: "Image formats",
		outputs: ["webp", "jpeg", "png", "avif", "gif", "bmp", "tiff", "ico", "mjpeg"],
		placeholder: "Any ffmpeg-readable image",
		runtime: "container",
		status: "available",
	},
	{
		aliases: [
			"slackmoji",
			"slack-emoji",
			"slack-emoji-converter",
			"emoji-to-gif",
			"animated-emoji-converter",
		],
		api: {
			accepts: IMAGE_REQUEST_FORMATS,
			examples: [
				{
					body: "file=@emoji.png; effect=none",
					contentType: "multipart/form-data",
					description: "Upload an image and generate an animated GIF.",
					method: "POST",
					url: "/api/slackmoji",
				},
				{
					description: "Check a queued slackmoji conversion job.",
					method: "GET",
					url: "/api/slackmoji?job=<job-id>",
				},
			],
			fields: [
				{
					description: "Target output format.",
					id: "outputFormat",
					required: true,
					values: ["gif"],
				},
				{
					description: "Optional bucket preset source key.",
					id: "sourceKey",
				},
				{
					description: "Optional animation preset.",
					id: "effect",
					values: [
						"none",
						"spinning",
						"flipping",
						"zoom",
						"slide_in",
						"slide_out",
						"scroll",
						"spin_left",
						"spin_right",
						"jitter",
						"rock",
						"pulse",
						"dance",
						"intensifies",
						"blink",
						"party",
						"loop",
						"zigzag",
						"yup",
						"excited",
						"nope",
						"dizzy",
						"spiral",
						"shrinking",
						"peeking",
						"hologram",
						"frazzled",
						"melting",
						"rave",
						"matrix",
						"bees",
						"deal_with_it",
						"glitch",
						"ripple",
						"pixelate",
						"glitch_out",
						"shattered",
						"portal",
						"origami",
						"paint_drip",
						"neon_pulse",
						"pixel_sort",
						"kaleidoscope",
						"bubble_pop",
						"typewriter",
						"black_hole",
						"mosaic_spin",
						"liquid_metal",
						"time_warp",
						"dna_spiral",
						"paint_splash",
						"rubiks",
						"vinyl_record",
						"blueprint",
					],
				},
			],
			methods: ["GET", "POST"],
			response: "json",
		},
		audience: "Media",
		description: "Create animated Slack-style GIFs from images in the ffmpeg container.",
		display: {
			actionLabel: "Generate Slack-style GIF",
			category: "Media",
			examples: [],
		},
		endpoint: "/api/slackmoji",
		id: "slackmoji",
		input: {
			accept: ["image/*", ".avif", ".bmp", ".gif", ".ico", ".jpg", ".jpeg", ".mjpeg", ".png", ".tif", ".tiff", ".webp"],
			label: "Image file",
			kind: "file",
			required: true,
		},
		label: "Slack-style GIF generator",
		outputs: ["gif"],
		placeholder: "Upload an image to animate as GIF",
		runtime: "container",
		status: "available",
	},
	{
		aliases: [
			"file-format",
			"text-file",
			"data-file",
			"json-to-csv",
			"csv-to-json",
			"json-to-yaml-converter",
			"yaml-to-json-converter",
			"json-to-toml-converter",
			"toml-to-json-converter",
			"xml-to-json-converter",
			"csv-to-sql-converter-inserts",
			"csv-to-excel-converter",
			"excel-json-to-csv-converter",
			"excel-xml-to-csv-converter",
			"json-to-sql-converter",
			"csv-to-yaml-converter",
			"yaml-to-csv-converter",
			"csv-to-toml-converter",
			"toml-to-csv-converter",
			"json-to-xml-converter",
			"xml-to-csv-converter",
			"yaml-to-toml-converter",
			"toml-to-yaml-converter",
			"yaml-to-xml-converter",
			"xml-to-yaml-converter",
			"env-to-toml-converter",
			"toml-to-env-converter",
			"ini-to-yaml-converter",
			"yaml-to-ini-converter",
			"properties-to-yaml-converter",
			"yaml-to-properties-converter",
			"tsv-to-csv-converter",
			"csv-to-tsv-converter",
		],
		api: {
			accepts: FILE_REQUEST_FORMATS,
			examples: [
				{
					body: "name,role\nAda,admin",
					contentType: "text/csv",
					description: "Post raw CSV and choose JSON output with query fields.",
					method: "POST",
					url: "/api/file-format?outputFormat=json&sourceName=people.csv",
				},
				{
					body: "file=@people.csv; outputFormat=json",
					contentType: "multipart/form-data",
					description: "Upload a file with a file field and outputFormat field.",
					method: "POST",
					url: "/api/file-format",
				},
			],
			fields: [
					{
						description: "Target text-file format.",
						id: "outputFormat",
						required: true,
						values: TEXT_FILE_FORMATS,
					},
				{
					description: "Optional source filename used for conversion context and download names.",
					id: "sourceName",
				},
			],
			methods: ["GET", "POST"],
			response: "json",
		},
		audience: "Media",
			description: "Convert text, Markdown, JSON, CSV, HTML, YAML, TOML, XML, INI, env, properties, and SQL files.",
		display: {
			actionLabel: "Convert file",
			category: "Files",
			examples: [],
		},
		id: "file-format",
		endpoint: "/api/file-format",
		input: {
				accept: ["text/plain", "text/markdown", "text/csv", "text/tab-separated-values", "text/html", "application/json", "application/xml", "application/yaml", "application/sql", ".txt", ".md", ".markdown", ".csv", ".tsv", ".tab", ".xls", ".html", ".json", ".yaml", ".yml", ".toml", ".xml", ".ini", ".properties", ".env", ".sql"],
			label: "Text file",
			kind: "file",
			required: true,
		},
		label: "Text file formats",
			outputs: TEXT_FILE_FORMATS,
			placeholder: "TXT, Markdown, JSON, CSV, HTML, YAML, TOML, XML, INI, env, properties, or SQL",
		runtime: "worker",
		status: "available",
	},
	{
			aliases: [
				"document-format",
				"document-convert",
				"docx-to-markdown",
				"markdown-to-docx",
				"md-to-docx",
				"html-to-docx",
				"docx-to-html",
				"markdown-to-wordpress-html-converter",
			],
		api: {
			accepts: DOCUMENT_REQUEST_FORMATS,
			examples: [
				{
					body: "file=@notes.md; outputFormat=docx",
					contentType: "multipart/form-data",
					description: "Upload a document and create a Pandoc conversion job.",
					method: "POST",
					url: "/api/document-format",
				},
				{
					description: "Check a queued document conversion job.",
					method: "GET",
					url: "/api/document-format?job=<job-id>",
				},
			],
			fields: [
				{
					description: "Target document format. The API accepts safe Pandoc output extensions.",
					id: "outputFormat",
					required: true,
					values: ["docx", "odt", "rtf", "epub", "html", "md", "txt"],
				},
			],
			methods: ["GET", "POST"],
			response: "json",
		},
		audience: "Documents",
		description: "Convert uploaded documents through the async Cloudflare Container running Pandoc.",
		display: {
			actionLabel: "Convert document",
			category: "Documents",
			examples: [],
		},
		endpoint: "/api/document-format",
		id: "document-format",
		input: {
			accept: [
				"application/epub+zip",
				"application/rtf",
				"application/vnd.oasis.opendocument.text",
				"application/vnd.openxmlformats-officedocument.wordprocessingml.document",
				"text/html",
				"text/markdown",
				"text/plain",
				".docx",
				".epub",
				".html",
				".md",
				".odt",
				".rtf",
				".txt",
			],
			label: "Document file",
			kind: "file",
			required: true,
		},
		label: "Document formats",
		outputs: ["docx", "odt", "rtf", "epub", "html", "md", "txt"],
		placeholder: "DOCX, ODT, RTF, EPUB, HTML, Markdown, or TXT",
		runtime: "container",
		status: "available",
	},
	{
			aliases: [
				"video-format",
				"video-transcode",
				"video-format-converter",
				"mp4-to-webm",
				"webm-to-mp4",
				"mov-to-mp4",
				"extract-audio-from-video",
				"video-audio-remover",
				"video-bitrate-changer",
				"video-compressor",
				"video-compressor-simple",
				"video-duration-cutter",
				"video-frame-extractor",
				"video-frame-sequence-exporter",
				"video-grayscale",
				"video-keyframe-extractor",
				"video-speed-changer",
				"video-thumbnail-generator",
				"change-video-fps",
				"resize-video-dimensions",
			],
		api: {
			accepts: VIDEO_REQUEST_FORMATS,
			examples: [
				{
					body: "file=@clip.mp4; outputFormat=webm",
					contentType: "multipart/form-data",
					description: "Upload a video file and create a conversion job.",
					method: "POST",
					url: "/api/video-format",
				},
				{
					description: "Check a queued video conversion job.",
					method: "GET",
					url: "/api/video-format?job=<job-id>",
				},
			],
			fields: [
				{
					description: "Target video, audio, or animated image format.",
					id: "outputFormat",
					required: true,
					values: ["mp4", "webm", "mov", "mkv", "avi", "m4v", "mpeg", "mpg", "ogv", "gif", "png", "webp", "jpeg", "mp3", "wav", "flac", "m4a", "ogg", "opus"],
				},
				{
					description: "Optional ffmpeg operation preset.",
					id: "operation",
					values: ["thumbnail", "extract-audio", "remove-audio", "resize", "trim", "grayscale"],
				},
				{
					description: "Optional timestamp, duration, fps, bitrate, width, height, speed, or volume fields.",
					id: "time",
				},
			],
			methods: ["GET", "POST"],
			response: "json",
		},
		audience: "Media",
		description: "Convert uploaded video through an async Cloudflare Container running ffmpeg.",
		display: {
			actionLabel: "Convert video",
			category: "Media",
			examples: [],
		},
		endpoint: "/api/video-format",
		id: "video-format",
		input: {
			accept: ["video/*", "audio/*", ".3gp", ".avi", ".flv", ".m4v", ".mkv", ".mov", ".mp4", ".mpeg", ".mpg", ".ogv", ".ts", ".webm", ".wmv"],
			label: "Video or audio file",
			kind: "file",
			required: true,
		},
		label: "Video and audio formats",
		outputs: ["mp4", "webm", "mov", "mkv", "avi", "m4v", "mpeg", "mpg", "ogv", "gif", "png", "webp", "jpeg", "mp3", "wav", "flac", "m4a", "ogg", "opus"],
		placeholder: "Any ffmpeg-readable video or audio",
		runtime: "container",
		status: "available",
	},
	{
			aliases: [
				"audio-format",
				"audio-transcode",
				"audio-format-converter",
				"mp3-to-wav",
				"wav-to-mp3",
				"mp3-to-flac",
				"flac-to-mp3",
				"wav-to-flac",
				"audio-bitrate-changer",
				"audio-channel-remover",
				"audio-mono-stereo-converter",
				"audio-sample-rate-converter",
				"audio-thumbnail-generator",
				"audio-trimmer",
				"audio-waveform-generator",
			],
		api: {
			accepts: AUDIO_REQUEST_FORMATS,
			examples: [
				{
					body: "file=@clip.mp3; outputFormat=wav",
					contentType: "multipart/form-data",
					description: "Upload an audio file and create a conversion job.",
					method: "POST",
					url: "/api/audio-format",
				},
				{
					description: "Check a queued audio conversion job.",
					method: "GET",
					url: "/api/audio-format?job=<job-id>",
				},
			],
			fields: [
				{
					description: "Target audio format. The API accepts any safe ffmpeg output extension.",
					id: "outputFormat",
					required: true,
					values: ["mp3", "wav", "flac", "aac", "m4a", "ogg", "opus", "aiff", "mka", "wma", "png"],
				},
				{
					description: "Optional ffmpeg operation preset.",
					id: "operation",
					values: ["trim", "waveform"],
				},
				{
					description: "Optional duration, bitrate, channels, sampleRate, speed, or volume fields.",
					id: "duration",
				},
			],
			methods: ["GET", "POST"],
			response: "json",
		},
		audience: "Media",
		description: "Convert uploaded audio through the async Cloudflare Container running ffmpeg.",
		display: {
			actionLabel: "Convert audio",
			category: "Media",
			examples: [],
		},
		endpoint: "/api/audio-format",
		id: "audio-format",
		input: {
			accept: ["audio/*", ".aac", ".aiff", ".flac", ".m4a", ".mka", ".mp3", ".oga", ".ogg", ".opus", ".wav", ".wma"],
			label: "Audio file",
			kind: "file",
			required: true,
		},
		label: "Audio formats",
		outputs: ["mp3", "wav", "flac", "aac", "m4a", "ogg", "opus", "aiff", "mka", "wma", "png"],
		placeholder: "Any ffmpeg-readable audio",
		runtime: "container",
		status: "available",
	},
];

export function listConverterTools() {
	return CONVERTER_TOOLS;
}

export function findConverterTool(type: string) {
	const normalisedType = type.trim().toLowerCase();
	return CONVERTER_TOOLS.find((tool) =>
		tool.id === normalisedType || tool.aliases.includes(normalisedType),
	);
}
